# Intrduction to scikit-learn (sklearn)
Demostration of the most useful functions of scikit learn library

What's we're going to cover : 

0. An end-to-end Scikit-Learn workflow
1. Get the data ready 
2. Choose the right estimator/algorithme for our problems
3. Fit the model/algorithme and use it to make predictions on our data
4. Evaluating a model 
5. Improve a model
6. Save and load a trained model
7. Putting it all together

## 0. An end-to-end scikit-learn workflow

In [1]:
whatsWerecovering = [
"0. An end-to-end Scikit-Learn workflow",
"1. Get the data ready ",
"2. Choose the right estimator/algorithm for our problems",
"3. Fit rh model/algorithme and use it to make predictions on our data",
"4. Evaluating a model" ,
"5. Improve a model",
"6. Save and load a trained model",
"7. Putting it all together"]

In [2]:
whatsWerecovering

['0. An end-to-end Scikit-Learn workflow',
 '1. Get the data ready ',
 '2. Choose the right estimator/algorithm for our problems',
 '3. Fit rh model/algorithme and use it to make predictions on our data',
 '4. Evaluating a model',
 '5. Improve a model',
 '6. Save and load a trained model',
 '7. Putting it all together']

In [3]:
# Standard imports
import pandas as pd
import numpy as np
import matplotlib as plt
%matplotlib inline

In [4]:
import warnings 
warnings.filterwarnings("ignore")

In [5]:
# 1. Get the data ready 
import pandas as pd
heartDisease = pd.read_csv('/home/rayani00/Bureau/python/MLPerso/zero-to-mastery-ml-master/data/heart-disease.csv')
heartDisease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [6]:
## To get the target in function of others attributes
# Create X (features matrix)
X = heartDisease.drop("target", axis=1)

# Create y (labels)
y = heartDisease["target"]


In [7]:
# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

# We'ell keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [8]:
# 3. Fit the model to the training data

from sklearn.model_selection import train_test_split
# train_test_split is an algorithm that splits data

# test_size means that 80% of data 
# Will be used for training
# 20% wille be used for testing
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [9]:
# We have to fit the data model we created
clf.fit(X_train,y_train);

In [10]:
# Make a prediction 
y_preds = clf.predict(X_test)
y_preds

array([0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1])

In [11]:
y_test

79     1
301    0
45     1
224    0
100    1
      ..
138    1
44     1
167    0
116    1
16     1
Name: target, Length: 61, dtype: int64

In [12]:
# 4. Evaluate the model on the trainig data and the test data
clf.score(X_train, y_train)

1.0

In [13]:
clf.score(X_test, y_test)

0.7868852459016393

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
classification_report()
print(classification_report(y_test,y_preds))

TypeError: classification_report() missing 2 required positional arguments: 'y_true' and 'y_pred'

In [29]:
confusion_matrix(y_test, y_preds)

array([[24, 11],
       [ 1, 25]])

In [30]:
accuracy_score(y_test, y_preds)

0.8032786885245902

In [31]:
# 5. Improve a model
# Try different amount of n_estimators
np.random.seed(42)
for i in range (10, 100, 10) : 
    print(f'Trying model with {i} estimators ..')
    clf = RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    print(f'Model accuracy on test set : {clf.score(X_test, y_test) * 100}')
    print('-----------')

Trying model with 10 estimators ..
Model accuracy on test set : 85.24590163934425
-----------
Trying model with 20 estimators ..
Model accuracy on test set : 70.49180327868852
-----------
Trying model with 30 estimators ..
Model accuracy on test set : 77.04918032786885
-----------
Trying model with 40 estimators ..
Model accuracy on test set : 80.32786885245902
-----------
Trying model with 50 estimators ..
Model accuracy on test set : 78.68852459016394
-----------
Trying model with 60 estimators ..
Model accuracy on test set : 78.68852459016394
-----------
Trying model with 70 estimators ..
Model accuracy on test set : 78.68852459016394
-----------
Trying model with 80 estimators ..
Model accuracy on test set : 80.32786885245902
-----------
Trying model with 90 estimators ..
Model accuracy on test set : 75.40983606557377
-----------


In [32]:
# 6. Save a model and load it
import pickle
pickle.dump(clf,open("random_forest_model_1.pkl","wb"))

In [33]:
loadedModel = pickle.load(open("random_forest_model_1.pkl","rb"))
loadedModel.score(X_test,y_test)

0.7540983606557377

In [34]:
import sklearn
sklearn.show_versions()


System:
    python: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]
executable: /home/rayani00/anaconda3/bin/python
   machine: Linux-5.8.0-55-generic-x86_64-with-glibc2.10

Python dependencies:
          pip: 21.1
   setuptools: 50.3.1.post20201107
      sklearn: 0.24.1
        numpy: 1.19.2
        scipy: 1.6.1
       Cython: 0.29.21
       pandas: 1.1.3
   matplotlib: 3.3.4
       joblib: 1.0.1
threadpoolctl: 2.1.0

Built with OpenMP: True


##  1- Getting our data ready to be used with machine learning
    Three main things we have to do  : 
        1. Spliting the data into features and labels (usually 'x' & 'y')
        2. Filling (also called imputing) or disregarding missing values 
        3. Converting non-numerical values into numerical values (also called feature encoding)

In [35]:
heartDisease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [36]:
# Get the features 
# axis = 1 : column axis
# axis = 0 : rows axis 
X = heartDisease.drop("target",axis=1)
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [37]:
# Get the labels
y = heartDisease.target
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [38]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split 

In [39]:
# It returns 4 arrays
# test_size is the size of the data we want to test 
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2)

In [40]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

##### As we can see 80% of the heart_disease rows go to our training model, and 20% goes to our test model 

## 1.1 Make sure it's all numerical 

In [41]:
car_sales = pd.read_csv("/home/rayani00/Bureau/python/MLPerso/zero-to-mastery-ml-master/data/car-sales-extended.csv")

In [42]:
car_sales.head

<bound method NDFrame.head of        Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]>

In [43]:
# Split into X and y
X =  car_sales.drop("Price", axis=1)
y = car_sales["Price"]

# Split into training and test data 
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [44]:
# Build machine learning model 
# Regressor predict a number

from sklearn.ensemble import RandomForestRegressor 
model = RandomForestRegressor()
model.fit(X_train,y_train)
model.score(X_test,y_test)


ValueError: could not convert string to float: 'Toyota'

In [23]:
X.head

<bound method NDFrame.head of        Make Colour  Odometer (KM)  Doors
0     Honda  White          35431      4
1       BMW   Blue         192714      5
2     Honda  White          84714      4
3    Toyota  White         154365      4
4    Nissan   Blue         181577      3
..      ...    ...            ...    ...
995  Toyota  Black          35820      4
996  Nissan  White         155144      3
997  Nissan   Blue          66604      4
998   Honda  White         215883      4
999  Toyota   Blue         248360      4

[1000 rows x 4 columns]>

In [36]:
# Turn the categorical features into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer 

categorical_features = ["Make", "Colour", "Doors"]
# One hot is the method we'll use in this case
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                   one_hot,
                                   categorical_features)],
                                   remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [38]:
# Let' put this data into a datafranme 
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [40]:
# We can also use dummies in pandas
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [43]:
# Let's refit the model 
np.random.seed(11)
X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                    y,
                                                    test_size=0.2)
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.2941031433819311

## 1.2 How to deal with missing values
1. Fille them with some values (Also called imputation)
2. Remove the rows that contains missing values

In [60]:
car_sales_missing = pd.read_csv("/home/rayani00/Bureau/python/MLPerso/zero-to-mastery-ml-master/data/car-sales-extended-missing-data.csv")

In [67]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [61]:
# Let's create X and y 
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [62]:
# Turn the categorical features into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer 

categorical_features = ["Make", "Colour", "Doors"]
# One hot is the method we'll use in this case
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                   one_hot,
                                   categorical_features)],
                                   remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

### Option 1  : Fill missing data with pandas

In [63]:
# Fill the "Make" column 
car_sales_missing["Make"].fillna("Missing", inplace=True)

# Fill the "Colour" column 
car_sales_missing["Colour"].fillna("Missing", inplace=True)

# Fill the "Odometer (KM)" column 
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(), inplace=True)

# Fill the "Doors" column 
car_sales_missing["Doors"].fillna(4, inplace=True)

In [64]:
car_sales_missing

Make Colour  Odometer (KM)  Doors    Price
0      Honda  White        35431.0    4.0  15323.0
1        BMW   Blue       192714.0    5.0  19943.0
2      Honda  White        84714.0    4.0  28343.0
3     Toyota  White       154365.0    4.0  13434.0
4     Nissan   Blue       181577.0    3.0  14043.0
..       ...    ...            ...    ...      ...
995   Toyota  Black        35820.0    4.0  32042.0
996  Missing  White       155144.0    3.0   5716.0
997   Nissan   Blue        66604.0    4.0  31570.0
998    Honda  White       215883.0    4.0   4001.0
999   Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [66]:
# Remove rows with missing Price value
car_sales_missing.dropna(inplace=True)

In [68]:
len(car_sales_missing)

950

##### After cleaning the data, let's test a model on it ! 

In [69]:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [72]:
# Turn the categorical features into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer 

categorical_features = ["Make", "Colour", "Doors"]
# One hot is the method we'll use in this case
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                   one_hot,
                                   categorical_features)],
                                   remainder="passthrough")

transformed_X = transformer.fit_transform(car_sales_missing)
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   
1    1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   
3    0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   
4    0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
945  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
946  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0   
947  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
948  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   
949  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

           14       15  
0     35431.0  15323.0  
1    192714.0  19943.0  
2     84714.0  28343.0  
3    154365.0  13434.0  
4    181577.0  14043.0  
..        ...      ...  
945   35820.0  32042.0  
946  155144.0   5716.0  
947   66604.0  31570.0  
948  215883.0   4001.0  
949  248360.0  12732.0  

[950 rows x 16 columns]

### Option 2 : Fill missing values with scikit-learn

In [74]:
car_sales_missing = pd.read_csv("/home/rayani00/Bureau/python/MLPerso/zero-to-mastery-ml-master/data/car-sales-extended-missing-data.csv")

In [78]:
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [77]:
# Drop the rows with no labels (Price column)
car_sales_missing.dropna(subset=["Price"], inplace=True)

In [79]:
# Split into X & y (Turn the data into label and features)
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing.Price

In [81]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorical values with missing and numerical with mean
cat_imputer = SimpleImputer(strategy="constant", fill_value="Missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer =  SimpleImputer(strategy="mean")

# Define columns 
cat_features = ["Make", "Colour"]
num_featues = ["Odometer (KM)"]
door_features = ["Doors"]

# Create an imputer (Something that automatically fills missing values)
imputer =  ColumnTransformer ([
    ("cat_imputer", cat_imputer, cat_features),
    ("num_imputer", num_imputer, num_featues),
    ("door_imputer", door_imputer, door_features)
])

# Transform the data 
filled_X = imputer.fit_transform(X)
filled_X

array([['Honda', 'White', 35431.0, 4.0],
       ['BMW', 'Blue', 192714.0, 5.0],
       ['Honda', 'White', 84714.0, 4.0],
       ...,
       ['Nissan', 'Blue', 66604.0, 4.0],
       ['Honda', 'White', 215883.0, 4.0],
       ['Toyota', 'Blue', 248360.0, 4.0]], dtype=object)

In [85]:
car_sales_filled = pd.DataFrame(filled_X,
                                columns=["Make", "Colour", "Odomter (KM)", "Doors"])

In [86]:
car_sales_filled.head()

Make Colour Odomter (KM) Doors
0   Honda  White        35431     4
1     BMW   Blue       192714     5
2   Honda  White        84714     4
3  Toyota  White       154365     4
4  Nissan   Blue       181577     3

In [87]:
car_sales_filled.isna().sum()

Make            0
Colour          0
Odomter (KM)    0
Doors           0
dtype: int64

In [88]:
# Turn the categorical features into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer 

categorical_features = ["Make", "Colour", "Doors"]
# One hot is the method we'll use in this case
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                   one_hot,
                                   categorical_features)],
                                   remainder="passthrough")

transformed_X = transformer.fit_transform(car_sales_filled)
pd.DataFrame(transformed_X)

0
0      (0, 1)\t1.0\n  (0, 10)\t1.0\n  (0, 12)\t1.0\...
1      (0, 0)\t1.0\n  (0, 6)\t1.0\n  (0, 13)\t1.0\n...
2      (0, 1)\t1.0\n  (0, 10)\t1.0\n  (0, 12)\t1.0\...
3      (0, 4)\t1.0\n  (0, 10)\t1.0\n  (0, 12)\t1.0\...
4      (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 11)\t1.0\n...
..                                                 ...
945    (0, 4)\t1.0\n  (0, 5)\t1.0\n  (0, 12)\t1.0\n...
946    (0, 2)\t1.0\n  (0, 10)\t1.0\n  (0, 11)\t1.0\...
947    (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 12)\t1.0\n...
948    (0, 1)\t1.0\n  (0, 10)\t1.0\n  (0, 12)\t1.0\...
949    (0, 4)\t1.0\n  (0, 6)\t1.0\n  (0, 12)\t1.0\n...

[950 rows x 1 columns]

In [89]:
# New we've got our data as numbers and no missing values 
# Let's fit a model
np.random.seed(11)
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)
model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.19185637276055656

## 2. Choosing the right estimator/algorithm for our problem

Scikit-Learn uses estimator as another term for machine learning model or algorithm

* Classification : predicting whether a sample is one thing or another
* Regression : predicting a number 


### 2.1 Picking a machine learning model for a regression problem

In [18]:
# Import Boston housing dataset 
from sklearn.datasets import load_boston
boston = load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [19]:
# Turn it into pandas data_frame
boston_df = pd.DataFrame(boston["data"], columns=boston["feature_names"])
boston_df["target"]=pd.Series(boston["target"])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [26]:
# How many samples do we have ? 
len (boston_df)

506

In [31]:
# Let's try the Ridge regression model
from sklearn.linear_model import Ridge

# Setup random seed
np.random.seed(18)

# Create the data 
X = boston_df.drop("target", axis=1)
y = boston_df.target

# Split the data into test and train sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instaciate the model
model = Ridge()
model.fit(X_train, y_train)

# Check the score 
model.score(X_test, y_test)

0.6886281562229689

In [30]:
# Let's try Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor

# Setup random seed
np.random.seed(18)

# Create the data 
X = boston_df.drop("target", axis=1)
y = boston_df.target

# Split the data into Test and Train sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instanciate the model that we gonna use
rf = RandomForestRegressor(n_estimators=100)
rf.fit(X_train, y_train)

# Check the score that we got
rf.score(X_test, y_test)

0.8951955888285864

### 2.2 Choosig an estimator model for a classification problem

In [50]:
# Import the data
heart_disease = pd.read_csv("/home/rayani00/Bureau/python/MLPerso/zero-to-mastery-ml-master/data/heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [51]:
# How many samples do we have ? 
len(heart_disease)

303

after consulting the map it says to try 'LinearSVC' 

In [52]:
# Import LinearSVC estimator class
from sklearn.svm import LinearSVC

# Setup random seed
np.random.seed(6)

# Create the Data 
X = heart_disease.drop("target", axis=1)
y = heart_disease.target

# Split the data into test and training sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instanciate the model
clf = LinearSVC()

# Train the model
clf.fit(X_train, y_train)

# Get the score of the model
clf.score(X_test, y_test)


0.639344262295082

In [37]:
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

In [53]:
# Try the RandomForestClassifier estimator class
# Import RandomForestClassifier estimator class
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(6)

# Create the Data 
X = heart_disease.drop("target", axis=1)
y = heart_disease.target

# Split the data into test and training sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instanciate the model 
clf = RandomForestClassifier(n_estimators=100)

# Fit the model to the data (Training machine learning model)
clf.fit(X_train, y_train)

# Get the score of the model (Use the patterns the model has learned)
clf.score(X_test, y_test)

0.8032786885245902

Tidbit:

1 - If you have structured data, used ensemble methods

2 - If you have unstructured data, use deep learning or transfer learning

## 3. Fit the model/algorithm on our data and use it to make predictions 
### 3.1 Fitting the model to the data
* "X" : Features, feature variables, data
* "y" : Labels, targets, target variables

### 3.2 Make predictions using a machine learning model
2 ways to make predictions : 
  * 'predict()'
  * 'predict_proba()'

In [54]:
# Use a trained model to make predictions 
clf.predict(np.array([1, 7, 8,3, 4])) # doesn't work ..

ValueError: Expected 2D array, got 1D array instead:
array=[1. 7. 8. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [57]:
X_test.shape

(61, 13)

In [56]:
y_test.shape

(61,)

In [59]:
clf.predict(X_test)

0.5245901639344263

In [61]:
# A way to calculate the accuracy
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

0.8032786885245902

In [62]:
# Check the accuracy 
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8032786885245902

#### Make predictions using predic_proba()

In [15]:
# predict_proba() returns probabilities of a classification label 
clf.predict_proba(X_test[:5])

array([[0.49, 0.51],
       [0.2 , 0.8 ],
       [0.08, 0.92],
       [0.49, 0.51],
       [0.55, 0.45]])

'predict()' can be used for regression models


In [19]:
from sklearn.datasets import load_boston
boston = load_boston()
# Turn it into pandas data_frame
boston_df = pd.DataFrame(boston["data"], columns=boston["feature_names"])
boston_df["target"]=pd.Series(boston["target"])

In [20]:
boston_df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

In [22]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(11)

# Create the data
X = boston_df.drop("target", axis=1)
y = boston_df.target

# Split into training and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instanciate and fit mode
model = RandomForestRegressor().fit(X_train, y_train)

# Make predictions
y_preds = model.predict(X_test)


In [25]:
# These are the predictions
y_preds[:10]

array([21.077, 14.636, 27.153, 34.671,  8.195, 13.741, 20.749,  8.369,
       45.462, 24.673])

In [27]:
# This is the truth
np.array(y_test[:10])

array([23.4,  8.1, 22. , 15. , 10.4, 14.9, 20.3,  8.4, 46. , 29.1])

In [28]:
# Let's compare the predictions to the truth
# The prediction will be that far away of the true result
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

2.7817745098039213

## 4. Evaluating a machine learning model

three ways to evalute Scikit-Learn models and estimators : 

1. Estimator 'score' method
2. The 'scoring' parameter
3. Problem-specific metric functions 

### 4.1 Evaluating a mode using the score method

In [38]:
from sklearn.ensemble import RandomForestClassifier 
# Import the data
heart_disease = pd.read_csv("/home/rayani00/Bureau/python/MLPerso/zero-to-mastery-ml-master/data/heart-disease.csv")

# Set up a random seed
np.random.seed(11)

# Create the data 
X = heart_disease.drop("target", axis=1)
y = heart_disease.target

# Split the data into train and test samples 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instanciate and fit the model
clf = RandomForestClassifier().fit(X_train, y_train)

In [39]:
clf.score(X_test, y_test)

0.8032786885245902

Let's do the same but for regression 

In [40]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(11)

# Create the data
X = boston_df.drop("target", axis=1)
y = boston_df.target

# Split into training and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instanciate and fit mode
model = RandomForestRegressor().fit(X_train, y_train)

# Make predictions
y_preds = model.predict(X_test)

In [41]:
model.score(X_test, y_test)

0.7653647106582748

### 4.2 Evaluating a model using scoring parameter

In [42]:
from sklearn.ensemble import RandomForestClassifier 
# Import the data
heart_disease = pd.read_csv("/home/rayani00/Bureau/python/MLPerso/zero-to-mastery-ml-master/data/heart-disease.csv")

# Set up a random seed
np.random.seed(11)

# Create the data 
X = heart_disease.drop("target", axis=1)
y = heart_disease.target

# Split the data into train and test samples 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instanciate and fit the model
clf = RandomForestClassifier().fit(X_train, y_train)

In [45]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf, X, y, cv=15)

array([0.9047619 , 0.85714286, 0.80952381, 0.85      , 0.9       ,
       0.95      , 0.85      , 0.85      , 0.8       , 0.85      ,
       0.65      , 0.9       , 0.7       , 0.75      , 0.8       ])

In [48]:
np.random.seed(11)

# Single training and test split score
clf_single_score = clf.score(X_test, y_test)

# Take the mean of 5-fold cross-validation score
clf_cross_val_score = np.mean(cross_val_score(clf, X, y, cv=5))

# Compare the two 
clf_single_score, clf_cross_val_score

(0.8032786885245902, 0.8150819672131148)

In [51]:
# Default scoring parameter of classifier = mean accuracy
clf.score(X_test, y_test)

0.8032786885245902

In [52]:
# Scoring parameter set to None by default
cross_val_score(clf, X, y, cv=5, scoring=None)

array([0.85245902, 0.90163934, 0.81967213, 0.8       , 0.76666667])

### Classification model evaluation metrics

1. Accuracy 
2. Area under ROC curve 
3. Confusion matrix
4. classification report 

In [57]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

# Set un a seed
np.random.seed(11)

# Create our data 
X = heart_disease.drop('target', axis=1)
y = heart_disease.target

# Split the data into train and test data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instanciate and fit the mode to our sets
clf = RandomForestClassifier()
clf.fit(X_test, y_test)

# Score 
cvs = cross_val_score(clf, X, y, cv=5)

# Calculate the mean accuracy 
print(f"heart disease classifier accuracy : {np.mean(cvs)*100:.2f}%")

heart disease classifier accuracy : 83.46%
